Главная страница
js-tasks-ru/htmlcss-20210916_kasss pull request #6
Opened 2021-09-25 08:38 UTC by RuslanKasyanov

Главная страница

2021-09-26 12:42 UTC, GSemikozov requested changes

2021-09-26 12:42 UTC, GSemikozov commented on pages/page.css
> +.page__header {
пока оставим как есть, но дальше - стили надо разнести по компонентам

2021-09-26 12:42 UTC, GSemikozov commented on pages/page.css
> +.page__footer__content {
это традиционная ошибка - элемента элемента, или "внучатый" элемент ) на самом деле правильнее записать так: .page__content_footer, или еще правильнее - это описать стили футера отдельно, и тогда - .footer__content

2021-09-26 20:40 UTC, RuslanKasyanov commented on pages/page.css
> +.page__header {
вынес в разные файлы -названные соответственно (надеюсь я правильно понял)

2021-09-26 20:41 UTC, RuslanKasyanov commented on pages/page.css
> +.page__footer__content {
описал отдельно

2021-09-27 15:10 UTC, GSemikozov requested changes

2021-09-27 15:10 UTC, GSemikozov commented on pages/footer.css
> +.footer_title {
тут и везде ниже - элемент в БЭМ пишем через 2 нижних подчеркивания, надо поправить) `__`

2021-09-28 05:59 UTC, RuslanKasyanov commented on pages/footer.css
> +.footer_title {
исправил

2021-09-29 20:32 UTC, GSemikozov approved these changes

2021-09-29 20:32 UTC, merged